// Meniul initial, generat din data/menu.js. Folosit o singura data, la
// prima pornire, pentru a popula baza de date. Dupa aceea sursa de adevar
// este baza de date, editabila din panoul de administrare.

export type ProdusSeed = {
  id: string;
  groupTitle: string;
  groupPrefix: string;
  withSizes: boolean;
  name: string;
  ingredients: string;
  weight: string;
  price: string | null;
  priceLarge: string | null;
  image: string;
  position: number;
};

export type CategorieSeed = {
  id: string;
  tab: string;
  title: string;
  note: string;
  image: string;
  position: number;
  items: ProdusSeed[];
};

const seed: CategorieSeed[] = [
  {
    "id": "pizza",
    "tab": "Pizza",
    "title": "Pizza",
    "note": "Blat pregătit în casă și copt la comandă. Toate pizzele sunt disponibile în două mărimi: normală 33 cm și family 50 cm.",
    "image": "/assets/img/art/pizza.svg",
    "position": 0,
    "items": [
      {
        "id": "pizza-margherita",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Margherita",
        "ingredients": "mozzarella, sos de roșii",
        "weight": "",
        "price": "30",
        "priceLarge": "65",
        "image": "/assets/img/produse/pizza-margherita.webp",
        "position": 0
      },
      {
        "id": "pizza-prosciutto",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Prosciutto",
        "ingredients": "mozzarella, sos de roșii, prosciutto",
        "weight": "",
        "price": "32",
        "priceLarge": "73",
        "image": "/assets/img/produse/pizza-prosciutto.webp",
        "position": 1
      },
      {
        "id": "pizza-salami",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Salami",
        "ingredients": "mozzarella, sos de roșii, salam",
        "weight": "",
        "price": "32",
        "priceLarge": "73",
        "image": "/assets/img/produse/pizza-salami.webp",
        "position": 2
      },
      {
        "id": "pizza-diavola",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Diavola",
        "ingredients": "mozzarella, sos de roșii, salam picant, ardei iute",
        "weight": "",
        "price": "35",
        "priceLarge": "75",
        "image": "/assets/img/produse/pizza-diavola.webp",
        "position": 3
      },
      {
        "id": "pizza-quattro-stagioni",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Quattro Stagioni",
        "ingredients": "mozzarella, sos roșii, salam, prosciutto, ciuperci, gogoșari, măsline",
        "weight": "",
        "price": "35",
        "priceLarge": "75",
        "image": "/assets/img/produse/pizza-quattro-stagioni.webp",
        "position": 4
      },
      {
        "id": "pizza-capriciosa",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Capriciosa",
        "ingredients": "mozzarella, sos de roșii, prosciutto, carciofi/anghinare, măsline felii",
        "weight": "",
        "price": "37",
        "priceLarge": "78",
        "image": "/assets/img/produse/pizza-capriciosa.webp",
        "position": 5
      },
      {
        "id": "pizza-salami-funghi",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Salami Funghi",
        "ingredients": "mozzarella, sos de roșii, salam, ciuperci",
        "weight": "",
        "price": "35",
        "priceLarge": "75",
        "image": "/assets/img/produse/pizza-salami-funghi.webp",
        "position": 6
      },
      {
        "id": "pizza-prosciutto-funghi",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Prosciutto Funghi",
        "ingredients": "mozzarella, sos de roșii, prosciutto, ciuperci, măsline",
        "weight": "",
        "price": "35",
        "priceLarge": "75",
        "image": "/assets/img/produse/pizza-prosciutto-funghi.webp",
        "position": 7
      },
      {
        "id": "pizza-polo",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Polo",
        "ingredients": "mozzarella, sos de roșii, ciuperci, piept de pui",
        "weight": "",
        "price": "38",
        "priceLarge": "80",
        "image": "/assets/img/produse/pizza-polo.webp",
        "position": 8
      },
      {
        "id": "pizza-tonno",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Tonno",
        "ingredients": "mozzarella, sos de roșii, ceapă roșie, ton",
        "weight": "",
        "price": "38",
        "priceLarge": "80",
        "image": "/assets/img/produse/pizza-tonno.webp",
        "position": 9
      },
      {
        "id": "pizza-rustica",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Rustica",
        "ingredients": "mozzarella, sos de roșii, prosciutto, salam, cârnat, ciuperci, ceapă roșie, gogoșar, porumb, ou, măsline",
        "weight": "",
        "price": "40",
        "priceLarge": "83",
        "image": "/assets/img/produse/pizza-rustica.webp",
        "position": 10
      },
      {
        "id": "pizza-quattro-formaggi",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Quattro Formaggi",
        "ingredients": "mozzarella, sos roșii, emmentaler, gorgonzola, parmezan",
        "weight": "",
        "price": "40",
        "priceLarge": "83",
        "image": "/assets/img/produse/pizza-quattro-formaggi.webp",
        "position": 11
      },
      {
        "id": "pizza-quattro-formaggi-salamino",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Quattro Formaggi Salamino",
        "ingredients": "mozzarella, sos roșii, emmentaler, gorgonzola, parmezan, salam picant",
        "weight": "",
        "price": "45",
        "priceLarge": "86",
        "image": "/assets/img/produse/pizza-quattro-formaggi-salamino.webp",
        "position": 12
      },
      {
        "id": "pizza-prosciutto-crudo-rucola",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Prosciutto Crudo Rucola",
        "ingredients": "mozzarella, sos de roșii, șuncă afumată, rucola, parmezan, roșii cherry",
        "weight": "",
        "price": "45",
        "priceLarge": "86",
        "image": "/assets/img/produse/pizza-prosciutto-crudo-rucola.webp",
        "position": 13
      },
      {
        "id": "pizza-hawaii",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Hawaii",
        "ingredients": "mozzarella, sos de roșii, prosciutto, ananas",
        "weight": "",
        "price": "35",
        "priceLarge": "75",
        "image": "/assets/img/produse/pizza-hawaii.webp",
        "position": 14
      },
      {
        "id": "pizza-vegetariana",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Vegetariană",
        "ingredients": "mozzarella, sos de roșii, ciuperci, gogoșar, porumb, măsline, capere, ceapă roșie",
        "weight": "",
        "price": "35",
        "priceLarge": "75",
        "image": "/assets/img/produse/pizza-vegetariana.webp",
        "position": 15
      },
      {
        "id": "pizza-fructe-de-mare",
        "groupTitle": "",
        "groupPrefix": "Pizza ",
        "withSizes": true,
        "name": "Fructe de mare",
        "ingredients": "mozzarella, sos de roșii, mix fructe de mare",
        "weight": "",
        "price": "50",
        "priceLarge": "100",
        "image": "/assets/img/produse/pizza-fructe-de-mare.webp",
        "position": 16
      }
    ]
  },
  {
    "id": "paste",
    "tab": "Paste",
    "title": "Paste",
    "note": "Paste proaspete, preparate zilnic în porții generoase.",
    "image": "/assets/img/art/paste.svg",
    "position": 1,
    "items": [
      {
        "id": "paste-carbonara",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Carbonara",
        "ingredients": "guanciale, ou, piper, parmezan",
        "weight": "400 g",
        "price": "45",
        "priceLarge": null,
        "image": "",
        "position": 0
      },
      {
        "id": "paste-arrabbiata",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Arrabbiata",
        "ingredients": "sos roșii, ardei iute, usturoi",
        "weight": "400 g",
        "price": "30",
        "priceLarge": null,
        "image": "",
        "position": 1
      },
      {
        "id": "paste-aglio-olio-peperoncino",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Aglio-Olio-Peperoncino",
        "ingredients": "usturoi, ardei iute, ulei, pătrunjel",
        "weight": "400 g",
        "price": "30",
        "priceLarge": null,
        "image": "",
        "position": 2
      },
      {
        "id": "paste-pesto",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Pesto",
        "ingredients": "sos pesto, busuioc, parmezan",
        "weight": "400 g",
        "price": "35",
        "priceLarge": null,
        "image": "",
        "position": 3
      },
      {
        "id": "paste-bolognese",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Bolognese",
        "ingredients": "sos Bolognez, pătrunjel, parmezan",
        "weight": "400 g",
        "price": "45",
        "priceLarge": null,
        "image": "",
        "position": 4
      },
      {
        "id": "paste-quattro-formaggi",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Quattro Formaggi",
        "ingredients": "gorgonzola, parmezan, ementaller, taleggio",
        "weight": "400 g",
        "price": "45",
        "priceLarge": null,
        "image": "",
        "position": 5
      },
      {
        "id": "paste-cu-creveti",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Paste cu creveți",
        "ingredients": "creveți, vin alb, pătrunjel, ulei măsline",
        "weight": "400 g",
        "price": "60",
        "priceLarge": null,
        "image": "",
        "position": 6
      },
      {
        "id": "paste-cu-fructe-de-mare",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Paste cu Fructe de Mare",
        "ingredients": "mix fructe de mare, vin alb, pătrunjel, ulei măsline",
        "weight": "450 g",
        "price": "70",
        "priceLarge": null,
        "image": "",
        "position": 7
      },
      {
        "id": "paste-cu-vongole",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Paste cu Vongole",
        "ingredients": "scoici, vin alb, pătrunjel, ulei măsline",
        "weight": "500 g",
        "price": "60",
        "priceLarge": null,
        "image": "",
        "position": 8
      },
      {
        "id": "taitei-de-orez-cu-crispy",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Teiței de orez cu Crispy",
        "ingredients": "teiței orez, legume, sos soia, piept pui, sos dulce-acrișor",
        "weight": "400 g",
        "price": "50",
        "priceLarge": null,
        "image": "",
        "position": 9
      }
    ]
  },
  {
    "id": "meniuri",
    "tab": "Meniuri",
    "title": "Meniuri",
    "note": "Meniuri complete, pregătite pentru pauza de prânz sau pentru o masă rapidă.",
    "image": "/assets/img/art/gratar.svg",
    "position": 2,
    "items": [
      {
        "id": "meniu-crispy",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Meniu Crispy",
        "ingredients": "4 buc. piept pui Crispy, cartofi pai, sos usturoi",
        "weight": "",
        "price": "40",
        "priceLarge": null,
        "image": "/assets/img/produse/meniu-crispy.webp",
        "position": 0
      },
      {
        "id": "meniu-aripioare",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Meniu Aripioare",
        "ingredients": "5 buc. aripioare pui, cartofi pai, sos usturoi",
        "weight": "",
        "price": "40",
        "priceLarge": null,
        "image": "/assets/img/produse/meniu-aripioare.webp",
        "position": 1
      },
      {
        "id": "meniul-zilei",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Meniul zilei",
        "ingredients": "ciorbă + felul 2",
        "weight": "",
        "price": "35",
        "priceLarge": null,
        "image": "/assets/img/produse/meniul-zilei.webp",
        "position": 2
      }
    ]
  },
  {
    "id": "burgeri",
    "tab": "Burgeri",
    "title": "Burgeri",
    "note": "Burgeri pregătiți la comandă, cu chiflă clasică sau neagră. Toți se servesc cu cartofi prăjiți.",
    "image": "/assets/img/art/burger.svg",
    "position": 3,
    "items": [
      {
        "id": "burger-pui",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Burger Pui",
        "ingredients": "chiflă, carne pui, sos burger, bacon, brânză cheddar, ceapă roșie, salată, cartofi prăjiți",
        "weight": "",
        "price": "35",
        "priceLarge": null,
        "image": "/assets/img/produse/burger-pui.webp",
        "position": 0
      },
      {
        "id": "burger-vita",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Burger Vită",
        "ingredients": "chiflă, carne vită Angus, sos burger, bacon, brânză cheddar, ceapă roșie, salată, cartofi prăjiți",
        "weight": "",
        "price": "45",
        "priceLarge": null,
        "image": "/assets/img/produse/burger-vita.webp",
        "position": 1
      },
      {
        "id": "burger-crispy",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Burger Crispy",
        "ingredients": "chiflă, carne pui Crispy, sos burger, bacon, brânză cheddar, ceapă roșie, salată, cartofi prăjiți",
        "weight": "",
        "price": "38",
        "priceLarge": null,
        "image": "/assets/img/produse/burger-crispy.webp",
        "position": 2
      },
      {
        "id": "black-burger-vita",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Black Burger Vită",
        "ingredients": "chiflă neagră, carne vită Angus, sos burger, bacon, brânză cheddar, ceapă roșie, salată, cartofi prăjiți",
        "weight": "",
        "price": "48",
        "priceLarge": null,
        "image": "/assets/img/produse/black-burger-vita.webp",
        "position": 3
      },
      {
        "id": "black-burger-pui",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Black Burger Pui",
        "ingredients": "chiflă neagră, carne pui, sos burger, bacon, brânză cheddar, ceapă roșie, salată, cartofi prăjiți",
        "weight": "",
        "price": "40",
        "priceLarge": null,
        "image": "/assets/img/produse/black-burger-pui.webp",
        "position": 4
      },
      {
        "id": "black-burger-crispy",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Black Burger Crispy",
        "ingredients": "chiflă neagră, carne pui Crispy, sos burger, bacon, brânză cheddar, ceapă roșie, salată, cartofi prăjiți",
        "weight": "",
        "price": "40",
        "priceLarge": null,
        "image": "/assets/img/produse/black-burger-crispy.webp",
        "position": 5
      }
    ]
  },
  {
    "id": "ciorbe",
    "tab": "Ciorbe",
    "title": "Ciorbe",
    "note": "Porție de 500 g, servită caldă.",
    "image": "/assets/img/art/ciorba.svg",
    "position": 4,
    "items": [
      {
        "id": "ciorba-de-burta",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Ciorbă de burtă",
        "ingredients": "",
        "weight": "500 g",
        "price": "25",
        "priceLarge": null,
        "image": "/assets/img/produse/ciorba-de-burta.webp",
        "position": 0
      },
      {
        "id": "ciorba-pui-a-la-grec",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Ciorbă de pui à la grec",
        "ingredients": "",
        "weight": "500 g",
        "price": "25",
        "priceLarge": null,
        "image": "/assets/img/produse/ciorba-pui-a-la-grec.webp",
        "position": 1
      },
      {
        "id": "ciorba-radauteana",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Ciorbă rădăuțeană",
        "ingredients": "",
        "weight": "500 g",
        "price": "25",
        "priceLarge": null,
        "image": "/assets/img/produse/ciorba-radauteana.webp",
        "position": 2
      },
      {
        "id": "smantana",
        "groupTitle": "Adaosuri",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Smântână",
        "ingredients": "",
        "weight": "",
        "price": "5",
        "priceLarge": null,
        "image": "/assets/img/produse/smantana.webp",
        "position": 3
      },
      {
        "id": "ardei-iute",
        "groupTitle": "Adaosuri",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Ardei iute",
        "ingredients": "",
        "weight": "",
        "price": "2",
        "priceLarge": null,
        "image": "/assets/img/produse/ardei-iute.webp",
        "position": 4
      },
      {
        "id": "paine",
        "groupTitle": "Adaosuri",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Pâine",
        "ingredients": "",
        "weight": "",
        "price": "1.5",
        "priceLarge": null,
        "image": "/assets/img/produse/paine.webp",
        "position": 5
      }
    ]
  },
  {
    "id": "gratare",
    "tab": "Grătare",
    "title": "Grătare",
    "note": "Preparate la grătar, alături de garnitura preferată.",
    "image": "/assets/img/art/gratar.svg",
    "position": 5,
    "items": [
      {
        "id": "ceafa-de-porc",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Ceafă de porc la grătar",
        "ingredients": "",
        "weight": "",
        "price": "35",
        "priceLarge": null,
        "image": "/assets/img/produse/ceafa-de-porc.webp",
        "position": 0
      },
      {
        "id": "piept-de-pui",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Piept de pui la grătar",
        "ingredients": "",
        "weight": "",
        "price": "35",
        "priceLarge": null,
        "image": "/assets/img/produse/piept-de-pui.webp",
        "position": 1
      },
      {
        "id": "pulpa-pui-dezosata",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Pulpă pui dezosată",
        "ingredients": "",
        "weight": "",
        "price": "35",
        "priceLarge": null,
        "image": "/assets/img/produse/pulpa-pui-dezosata.webp",
        "position": 2
      }
    ]
  },
  {
    "id": "garnituri",
    "tab": "Garnituri",
    "title": "Garnituri",
    "note": "Se comandă alături de preparatele la grătar sau separat.",
    "image": "/assets/img/art/paste.svg",
    "position": 6,
    "items": [
      {
        "id": "risotto",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Risotto",
        "ingredients": "orez, parmezan, unt, vin alb",
        "weight": "380 g",
        "price": "40",
        "priceLarge": null,
        "image": "/assets/img/produse/risotto.webp",
        "position": 0
      },
      {
        "id": "sos-de-ciuperci",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Sos de ciuperci cu smântână",
        "ingredients": "",
        "weight": "350 g",
        "price": "35",
        "priceLarge": null,
        "image": "/assets/img/produse/sos-de-ciuperci.webp",
        "position": 1
      },
      {
        "id": "legume-la-gratar",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Legume la grătar",
        "ingredients": "",
        "weight": "200 g",
        "price": "15",
        "priceLarge": null,
        "image": "/assets/img/produse/legume-la-gratar.webp",
        "position": 2
      },
      {
        "id": "cartofi-natur",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Cartofi natur",
        "ingredients": "",
        "weight": "200 g",
        "price": "15",
        "priceLarge": null,
        "image": "/assets/img/produse/cartofi-natur.webp",
        "position": 3
      },
      {
        "id": "cartofi-wedges",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Cartofi wedges",
        "ingredients": "",
        "weight": "200 g",
        "price": "15",
        "priceLarge": null,
        "image": "/assets/img/produse/cartofi-wedges.webp",
        "position": 4
      },
      {
        "id": "cartofi-pai",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Cartofi pai",
        "ingredients": "",
        "weight": "150 g",
        "price": "15",
        "priceLarge": null,
        "image": "/assets/img/produse/cartofi-pai.webp",
        "position": 5
      }
    ]
  },
  {
    "id": "salate",
    "tab": "Salate",
    "title": "Salate",
    "note": "Salate proaspete, pregătite la comandă.",
    "image": "/assets/img/art/salata.svg",
    "position": 7,
    "items": [
      {
        "id": "salata-asortata",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Salată asortată",
        "ingredients": "roșii, castraveți, ceapă, ardei",
        "weight": "250 g",
        "price": "13",
        "priceLarge": null,
        "image": "/assets/img/produse/salata-asortata.webp",
        "position": 0
      },
      {
        "id": "salata-varza",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Salată varză",
        "ingredients": "",
        "weight": "200 g",
        "price": "13",
        "priceLarge": null,
        "image": "/assets/img/produse/salata-varza.webp",
        "position": 1
      },
      {
        "id": "salata-rosii",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Salată roșii",
        "ingredients": "",
        "weight": "200 g",
        "price": "13",
        "priceLarge": null,
        "image": "/assets/img/produse/salata-rosii.webp",
        "position": 2
      },
      {
        "id": "salata-verde",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Salată verde",
        "ingredients": "",
        "weight": "120 g",
        "price": "13",
        "priceLarge": null,
        "image": "/assets/img/produse/salata-verde.webp",
        "position": 3
      },
      {
        "id": "ardei-copti",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Ardei copți",
        "ingredients": "",
        "weight": "150 g",
        "price": "13",
        "priceLarge": null,
        "image": "/assets/img/produse/ardei-copti.webp",
        "position": 4
      },
      {
        "id": "salata-cu-crispy",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Salată cu crispy",
        "ingredients": "salată iceberg, roșii, castraveți, feta, dressing, piept pui",
        "weight": "",
        "price": "50",
        "priceLarge": null,
        "image": "/assets/img/produse/salata-cu-crispy.webp",
        "position": 5
      },
      {
        "id": "salata-cu-ton",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Salată cu ton",
        "ingredients": "salată iceberg, ceapă roșie, porumb, lămâie",
        "weight": "",
        "price": "50",
        "priceLarge": null,
        "image": "/assets/img/produse/salata-cu-ton.webp",
        "position": 6
      }
    ]
  },
  {
    "id": "bar",
    "tab": "Bar",
    "title": "Bar",
    "note": "Cafea, băuturi răcoritoare și bere.",
    "image": "/assets/img/art/bautura.svg",
    "position": 8,
    "items": [
      {
        "id": "espresso-scurt",
        "groupTitle": "Băuturi calde",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Cafea expresso scurt",
        "ingredients": "",
        "weight": "30 ml",
        "price": "10",
        "priceLarge": null,
        "image": "/assets/img/produse/espresso-scurt.webp",
        "position": 0
      },
      {
        "id": "espresso-lung",
        "groupTitle": "Băuturi calde",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Cafea expresso lung",
        "ingredients": "",
        "weight": "60 ml",
        "price": "10",
        "priceLarge": null,
        "image": "/assets/img/produse/espresso-lung.webp",
        "position": 1
      },
      {
        "id": "cafea-lunga",
        "groupTitle": "Băuturi calde",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Cafea lungă",
        "ingredients": "",
        "weight": "100 ml",
        "price": "10",
        "priceLarge": null,
        "image": "/assets/img/produse/cafea-lunga.webp",
        "position": 2
      },
      {
        "id": "cappuccino",
        "groupTitle": "Băuturi calde",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Cappuccino",
        "ingredients": "",
        "weight": "150 ml",
        "price": "10",
        "priceLarge": null,
        "image": "/assets/img/produse/cappuccino.webp",
        "position": 3
      },
      {
        "id": "latte-macchiato",
        "groupTitle": "Băuturi calde",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Latte Macchiato",
        "ingredients": "",
        "weight": "150 ml",
        "price": "15",
        "priceLarge": null,
        "image": "/assets/img/produse/latte-macchiato.webp",
        "position": 4
      },
      {
        "id": "ceai",
        "groupTitle": "Băuturi calde",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Ceai",
        "ingredients": "mentă, fructe de pădure, negru",
        "weight": "",
        "price": "8",
        "priceLarge": null,
        "image": "/assets/img/produse/ceai.webp",
        "position": 5
      },
      {
        "id": "ciocolata-calda",
        "groupTitle": "Băuturi calde",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Ciocolată caldă",
        "ingredients": "",
        "weight": "150 ml",
        "price": "15",
        "priceLarge": null,
        "image": "/assets/img/produse/ciocolata-calda.webp",
        "position": 6
      },
      {
        "id": "cafe-frappe",
        "groupTitle": "Cafea la gheață, limonadă și fresh",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Café Frappé",
        "ingredients": "",
        "weight": "300 ml",
        "price": "20",
        "priceLarge": null,
        "image": "/assets/img/produse/cafe-frappe.webp",
        "position": 7
      },
      {
        "id": "ice-caffe",
        "groupTitle": "Cafea la gheață, limonadă și fresh",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Ice Caffè",
        "ingredients": "",
        "weight": "300 ml",
        "price": "15",
        "priceLarge": null,
        "image": "/assets/img/produse/ice-caffe.webp",
        "position": 8
      },
      {
        "id": "limonada",
        "groupTitle": "Cafea la gheață, limonadă și fresh",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Limonadă",
        "ingredients": "",
        "weight": "400 ml",
        "price": "15",
        "priceLarge": null,
        "image": "/assets/img/produse/limonada.webp",
        "position": 9
      },
      {
        "id": "fresh-portocale",
        "groupTitle": "Cafea la gheață, limonadă și fresh",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Fresh portocale",
        "ingredients": "",
        "weight": "250 ml",
        "price": "20",
        "priceLarge": null,
        "image": "/assets/img/produse/fresh-portocale.webp",
        "position": 10
      },
      {
        "id": "coca-cola",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Coca Cola",
        "ingredients": "",
        "weight": "250 ml",
        "price": "10",
        "priceLarge": null,
        "image": "/assets/img/produse/coca-cola.webp",
        "position": 11
      },
      {
        "id": "coca-cola-zero",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Coca Cola Zero",
        "ingredients": "",
        "weight": "250 ml",
        "price": "10",
        "priceLarge": null,
        "image": "/assets/img/produse/coca-cola-zero.webp",
        "position": 12
      },
      {
        "id": "pepsi",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Pepsi Cola",
        "ingredients": "",
        "weight": "250 ml",
        "price": "10",
        "priceLarge": null,
        "image": "/assets/img/produse/pepsi.webp",
        "position": 13
      },
      {
        "id": "fanta",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Fanta",
        "ingredients": "portocale, lemon, struguri",
        "weight": "250 ml",
        "price": "10",
        "priceLarge": null,
        "image": "/assets/img/produse/fanta.webp",
        "position": 14
      },
      {
        "id": "sprite",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Sprite",
        "ingredients": "",
        "weight": "250 ml",
        "price": "10",
        "priceLarge": null,
        "image": "/assets/img/produse/sprite.webp",
        "position": 15
      },
      {
        "id": "schweppes",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Schweppes",
        "ingredients": "kinley, mandarine, bitter lemon",
        "weight": "250 ml",
        "price": "12",
        "priceLarge": null,
        "image": "/assets/img/produse/schweppes.webp",
        "position": 16
      },
      {
        "id": "cappy",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Cappy",
        "ingredients": "pere, piersici, portocale",
        "weight": "250 ml",
        "price": "12",
        "priceLarge": null,
        "image": "/assets/img/produse/cappy.webp",
        "position": 17
      },
      {
        "id": "fuzetea",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Fuzetea",
        "ingredients": "lămâie, piersică",
        "weight": "250 ml",
        "price": "12",
        "priceLarge": null,
        "image": "/assets/img/produse/fuzetea.webp",
        "position": 18
      },
      {
        "id": "apa-330",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Apă minerală/plată sticlă",
        "ingredients": "",
        "weight": "330 ml",
        "price": "10",
        "priceLarge": null,
        "image": "/assets/img/produse/apa-330.webp",
        "position": 19
      },
      {
        "id": "apa-750",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Apă minerală/plată sticlă",
        "ingredients": "",
        "weight": "750 ml",
        "price": "15",
        "priceLarge": null,
        "image": "/assets/img/produse/apa-750.webp",
        "position": 20
      },
      {
        "id": "bere",
        "groupTitle": "Răcoritoare, apă și bere",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Bere Peroni/Stella Artois sticlă",
        "ingredients": "",
        "weight": "0,33 l",
        "price": "12",
        "priceLarge": null,
        "image": "/assets/img/produse/bere.webp",
        "position": 21
      }
    ]
  },
  {
    "id": "deserturi",
    "tab": "Deserturi",
    "title": "Desert",
    "note": "Final dulce pentru masa ta.",
    "image": "/assets/img/art/desert.svg",
    "position": 9,
    "items": [
      {
        "id": "amandina",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Amandină",
        "ingredients": "",
        "weight": "",
        "price": "12",
        "priceLarge": null,
        "image": "/assets/img/produse/amandina.webp",
        "position": 0
      },
      {
        "id": "savarina",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Savarină",
        "ingredients": "",
        "weight": "",
        "price": "20",
        "priceLarge": null,
        "image": "/assets/img/produse/savarina.webp",
        "position": 1
      },
      {
        "id": "rulada-pavlova",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Ruladă Pavlova",
        "ingredients": "",
        "weight": "",
        "price": "15",
        "priceLarge": null,
        "image": "/assets/img/produse/rulada-pavlova.webp",
        "position": 2
      },
      {
        "id": "tiramisu",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Tiramisu",
        "ingredients": "",
        "weight": "",
        "price": "20",
        "priceLarge": null,
        "image": "/assets/img/produse/tiramisu.webp",
        "position": 3
      },
      {
        "id": "cheesecake",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Cheesecake",
        "ingredients": "",
        "weight": "",
        "price": "20",
        "priceLarge": null,
        "image": "/assets/img/produse/cheesecake.webp",
        "position": 4
      },
      {
        "id": "papanasi",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Papanași",
        "ingredients": "",
        "weight": "",
        "price": "20",
        "priceLarge": null,
        "image": "/assets/img/produse/papanasi.webp",
        "position": 5
      },
      {
        "id": "lava-cake",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Lava cake",
        "ingredients": "",
        "weight": "",
        "price": "20",
        "priceLarge": null,
        "image": "/assets/img/produse/lava-cake.webp",
        "position": 6
      },
      {
        "id": "cupa-inghetata",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Cupă înghețată",
        "ingredients": "",
        "weight": "",
        "price": "12",
        "priceLarge": null,
        "image": "/assets/img/produse/cupa-inghetata.webp",
        "position": 7
      }
    ]
  },
  {
    "id": "sosuri",
    "tab": "Sosuri",
    "title": "Sosuri",
    "note": "Sosuri la porție, pregătite în casă. Se comandă alături de orice preparat sau separat.",
    "image": "/assets/img/art/sos.svg",
    "position": 10,
    "items": [
      {
        "id": "sos-smantana-usturoi",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Sos smântână cu usturoi",
        "ingredients": "",
        "weight": "",
        "price": "6",
        "priceLarge": null,
        "image": "/assets/img/produse/sos-smantana-usturoi.svg",
        "position": 0
      },
      {
        "id": "sos-maioneza-usturoi",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Sos maioneză cu usturoi",
        "ingredients": "",
        "weight": "",
        "price": "5",
        "priceLarge": null,
        "image": "/assets/img/produse/sos-maioneza-usturoi.svg",
        "position": 1
      },
      {
        "id": "sos-rosii-dulce",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Sos roșii dulce",
        "ingredients": "",
        "weight": "",
        "price": "5",
        "priceLarge": null,
        "image": "/assets/img/produse/sos-rosii-dulce.svg",
        "position": 2
      },
      {
        "id": "sos-pikant",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Sos pikant",
        "ingredients": "",
        "weight": "",
        "price": "5",
        "priceLarge": null,
        "image": "/assets/img/produse/sos-pikant.svg",
        "position": 3
      },
      {
        "id": "sos-barbeque",
        "groupTitle": "",
        "groupPrefix": "",
        "withSizes": false,
        "name": "Sos barbeque",
        "ingredients": "",
        "weight": "",
        "price": "7",
        "priceLarge": null,
        "image": "/assets/img/produse/sos-barbeque.svg",
        "position": 4
      }
    ]
  }
];

export default seed;
